### PR TITLE
Just some minor edits to ready numbits for PyPI 😁.

### PR DESCRIPTION
**Pull request by astrogewgaw**
I just:

* added a LICENSE (MIT)
* added a MANIFEST.in file
* added a .gitignore
* added a setup.cfg file
* added more metadata to the setup.py file
* added a GitHub Action for testing numbits.
* carried out minor linting changes (most of them were automatically carried out by VSCode 😅)

I tried to add versioning and support for coveralls but it didn't work 😞. 

I know that you are waiting for [**sigprocpy**](https://github.com/FRBs/sigpyproc3) to add a LICENSE so that you can decide which LICENSE to use and release the package on PyPI accordingly. If they decide to go for another LICENSE, I will make the corresponding change 😄. This PR merely aims to (hopefully) make the release to PyPI easier. 

I was thinking of making exactly this package myself (because I needed packing/unpacking for [**priwo**](https://github.com/astrogewgaw/priwo)) and then I found this out of the blue, so thanks for making this 😁! I hope that **numbits** comes to PyPI soon.

Do let me know if there are any issues with this PR.

**NOTE**: If you decide to merge this, you will have to make a change to the tests badge in the README, since right now the GitHub Action is running for my fork, and not your original repository, so the badge links have to be changed 😅.

### CODE REVIEW

**Comment by telegraphic** [comment]
Beautiful 🌈. Thanks @astrogewgaw, I'm happy to merge and will try and get up on pypi asap. 

PS: Do you happen to have any experience with manylinux wheel building? There's a github action (https://github.com/RalfG/python-wheels-manylinux-build) I was thinking of trying to setup for projects like this.

**Comment by astrogewgaw** [comment]
Hey @telegraphic 👋🏾 ! Glad to know that everything is fine with PR #4! I don't know much about manylinux wheel building but I can definitely find out. Let me get back to you if I find anything useful. Looking forward to the PyPI release 😁!

**Comment by telegraphic** [comment]
Hey @astrogewgew, there is now a pypi release and `pip install numbits` seems to work.

**Comment by astrogewgaw** [comment]
That's awesome 😁 @telegraphic! I just installed it on my system and things seem to be working perfectly 👍🏾. I will be adding this as a dependency on [**priwo**](https://github.com/astrogewgaw/priwo) soon.

**Pull request merged**
